# This workflow is responsible for regenerating the IRI stem report
# It runs on a schedule and triggers the regeneration process

name: Regenerate IRI stem report
on:
  push:
  workflow_dispatch:

jobs:
  update-report:
    runs-on: ubuntu-latest

    name: "Regenerate IRI stem report"

    steps:
      # Retrieve the UTG GitHub repository.
      - name: Retrieve UTG repository
        # TODO: We should really be using https://gitlab.hl7.org/hl7/UTG.git instead of
        # the GitHub mirror, which is slightly out of date, but GitHub Action can't seem
        # to see it.
        run: mkdir -p tmp/hl7-utg && git clone --depth 1 https://github.com/HL7/UTG.git tmp/hl7-utg

      # Get ready to run scripts/utg/extract-utg-identifiers.py
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7

      # Generate the report.
      - name: Generate IRI stem report
        run: uv run scripts/utg/extract-utg-identifiers.py --id-type iri-stem tmp/hl7-utg -o tmp/utg-iri-stem-report.csv -f markdown

      # Display the report.
      - name: Display IRI stem report
        run: cat tmp/utg-iri-stem-report.md
